### ISSUE TITLE
Hello! Thank you!

### ISSUE THREAD

**Issue by dannyrb** [Glutanimate/hunspell-en-med-glut#4]
Thank you for sharing this! We were able to use it, along with a .NET Core NuGet package, to add spell checking to our Web Application.

It's not much, but I've put in a request for a small donation to be sent your way (via your website). Thanks again for making our lives a little bit easier (:

**Comment by glutanimate** [comment]
Thank you, Danny! I really appreciate the support. Glad to hear that you guys found the dictionary to be useful :) !
